name: Collector
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  GOPROXY: https://proxy.golang.org,direct
  GOSUMDB: sum.golang.org

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.21.3'

    - name: Display Go version
      run: go version

    - name: Download dependencies
      run: go mod download -x

    - name: Tidy dependencies (ensure go.sum is correct)
      run: go mod tidy

    - name: Build Go app
      run: go build -v -o myapp

    - name: Run collector
      run: ./myapp -sort -clash

    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@v4.1.0
      with:
        subject-path: 'myapp'

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add telegram/ subscription/ mixed/ daily_archive/ all_configs/ config_cache.json clash-config.yaml stats.json go.sum links.txt
        git diff --staged --quiet || git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"

    - name: Push changes
      uses: ad-m/github-push-action@v1.1.0
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: false
