name: Collector
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # <-- برای رفع اخطار Node.js 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.21.3'

    - name: Display Go version
      run: go version

    - name: Download dependencies
      run: go mod download

    - name: Tidy dependencies   # <-- مرحله جدید برای رفع missing go.sum entry
      run: go mod tidy

    - name: Build Go app
      run: go build -o myapp

    - name: Run collector
      run: ./myapp -sort -clash   # فلگ‌های دیگر مثل -dedup را هم می‌توانید اضافه کنید

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add telegram/ subscription/ mixed/ daily_archive/ config_cache.json clash-config.yaml stats.json
        git diff --staged --quiet || git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"

    - name: Push changes
      uses: ad-m/github-push-action@v1.1.0
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: false
